language: node_js
node_js:
  - "stable"
addons:
  apt:
    packages:
      - libgconf-2-4
services:
  - docker
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
env:
  - CI=true CHOKIDAR_USEPOLLING=1
before_install:
  #- docker pull jboss/keycloak
  #- docker run -d -p 8080:8080 -v $(pwd)/keycloack:/realm -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e KEYCLOAK_IMPORT=/realm/sume.json jboss/keycloak
  # Fixes an issue where the max file watch count is exceeded, triggering ENOSPC
  # https://stackoverflow.com/questions/22475849/node-js-error-enospc#32600959
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
script:
  - npm run lint
  - npm run test --passWithNoTests
  - npm run test --coverage --watchAll=false
  #- npm run test:e2e:ci
  - npm run build

