version: '3.3'

services:

  frontend:
    stdin_open: true
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - AUTH_ENDPOINT=http://sso:8080

  sso:
    image: jboss/keycloak
    ports: 
      - 8080:8080
    environment: 
      - KEYCLOAK_USER=admin 
      - KEYCLOAK_PASSWORD=admin 
      - KEYCLOAK_IMPORT=/realm/sume.json
    volumes:
      - ./keycloack:/realm
