version: '3.3'

services:

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - 8081:8080

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - 8082:8080
    volumes:
      - ./data/account-api.yaml:/account-api.yaml
    environment:
      SWAGGER_JSON: /account-api.yaml

  # Fake APIs

  catalog-api:
    container_name: "catalog-api"
    image: muonsoft/openapi-mock
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/swagger/catalog-api.yaml'
      OPENAPI_MOCK_PORT: 8001
    volumes:
      - ./data/catalog-api.yaml:/swagger/catalog-api.yaml
    ports:
      - 8001:8001
    