version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn install
      - run:
          name: Executing lint
          command: yarn lint
  test-unit:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn install
      - run:
          name: "Creating .env"
          command: echo "SKIP_PREFLIGHT_CHECK=true" > .env
      - run:
          name: "Executing unit tests"
          command: yarn test --collectCoverage=true --watchAll=false
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test-unit:
          requires:
            - lint
